changelog:
  rel_path: "changelog.md"
  overview:
    pattern: '### \[Unreleased\]([\s\S]*)### \[{{ old_version }}]'
    jinja_rel_path: .cl.overview.jinja2

  links:
    pattern: '\[Unreleased\]:.*\n'
    jinja_rel_path: .cl.links.jinja2

versioned_files:
  - rel_path: "pyproject.toml"
    pattern: 'version = "{{ old_version }}"'
    jinja: 'version = "{{ new_version }}"'
