files:
  - rel_path: CHANGELOG.md
    pattern: '### \[Unreleased\]([\s\S]*)### \[{{ version }}]'
    jinja_rel_path: .CHANGELOG.md.overview.jinja2
  - rel_path: CHANGELOG.md
    pattern: '\[Unreleased\]:.*\n'
    jinja_rel_path: .CHANGELOG.md.links.jinja2
    context:
      repo: klaviyo/woocommerce-klaviyo
