changelog:
  overview:
    pattern: '### \[Unreleased\]([\s\S]*)### \[{{ old_version }}]'
    jinja_rel_path: .cl.overview.jinja2

  links:
    pattern: '\[Unreleased\]:.*\n'
    jinja_rel_path: .cl.links.jinja2
