changelog:
  - pattern: '### \[Unreleased\]([\s\S]*)### \[{{ old_version }}]'
    jinja_rel_path: assets/.cl.overview.jinja2

  - pattern: '\[Unreleased\]:.*\n'
    jinja_rel_path: assets/.cl.links.jinja2
